name: Build
on: [ push ]
jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
      ARTIFACT: "playground"
      IM_ARTIFACTORY_EMAIL_EXCUSE: noreply-github@wartsila.com
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run docker build
        run: |
          make docker-build

      - name: Run docker container
        run: |
          make docker-run

      - name: Run docker test
        run: |
          make docker-test

      - name: Set environment variables based on branch
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          cat >> $GITHUB_ENV <<EOF
          BUILD_NUMBER=${GITHUB_RUN_NUMBER}
          BRANCH_NAME=${BRANCH_NAME}
          REGISTRY=${DOCKER_REGISTRY}
          EOF

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: DOCKER_REGISTRY
          username: DOCKER_USERNAME
          password: DOCKER_PASSWORD

      - name: Run docker push
        run: |
          make docker-push