name: Build
on: [ push ]
jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
#      DOCKER_REGISTRY: "registry.hub.docker.com"
      DOCKER_REGISTRY: "truongtuanduong"
      DOCKER_USERNAME: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
      ARTIFACT: "playground"
      IM_ARTIFACTORY_EMAIL_EXCUSE: "duong020202@gmail.com"
      HELM_EXPERIMENTAL_OCI: 1
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.7.1'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up yarn
        run: npm install -g yarn

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # If it is Docker Hub, no need to provide hub registry URL, otherwise, registry address is required
#          registry: "${{ env.DOCKER_REGISTRY }}"
          username: "${{ env.DOCKER_USERNAME }}"
          password: "${{ env.DOCKER_PASSWORD }}"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('*.lock') }}
          path: |
            my-app/build
            my-app/node_modules
          restore-keys:
            ${{ runner.os }}-

      - name: Set environment variables based on branch
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          cat >> $GITHUB_ENV <<EOF
          BUILD_NUMBER=${GITHUB_RUN_NUMBER}
          BRANCH_NAME=${BRANCH_NAME}
          REGISTRY=${DOCKER_REGISTRY}
          EOF

      - name: Yarn install dependencies
        run: |
          make install-dependencies

      - name: Yarn check code format
        run: |
          make check-code-format

      - name: Yarn build
        run: |
          make yarn-build

      - name: Run docker build
        run: |
          make docker-build

      - name: Run docker container
        run: |
          make docker-run

      - name: Run docker test
        run: |
          make docker-test

      - name: Run docker push
        run: |
          make docker-push