name: Build
on: [ push ]
jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: "registry.hub.docker.com"
      DOCKER_USERNAME: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
      ARTIFACT: "playground"
      IM_ARTIFACTORY_EMAIL_EXCUSE: "duong020202@gmail.com"
      HELM_EXPERIMENTAL_OCI: 1
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
#          registry: "${{ env.DOCKER_REGISTRY }}"
          username: "${{ env.DOCKER_USERNAME }}"
          password: "${{ env.DOCKER_PASSWORD }}"

      - name: Set environment variables based on branch
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          cat >> $GITHUB_ENV <<EOF
          BUILD_NUMBER=${GITHUB_RUN_NUMBER}
          BRANCH_NAME=${BRANCH_NAME}
          REGISTRY=${DOCKER_REGISTRY}
          EOF

      - name: Run docker build
        run: |
          make docker-build

      - name: Run docker container
        run: |
          make docker-run

      - name: Run docker test
        run: |
          make docker-test

      - name: Run docker push
        run: |
          make docker-push